'use strict';

function buildGuides(cfg) {
  return [
    [
      `# 🤖 COMPLETE BOT SETUP GUIDE`,
      '',
      `Your server has been fully built. Follow these guides to set up every bot.`,
      `After inviting each bot: right-click it in the member list → Roles → assign its bot role.`,
      '',
      `**Bots you need:**`,
      `1️⃣ Dante Bot (already running)`,
      `2️⃣ Carl-bot — reaction roles`,
      `3️⃣ ClashKing — war tracking, legend, clan management`,
      `4️⃣ ClashPerk — stats, CWL, donation tracker`,
      `5️⃣ YouTube alerts (free via IFTTT)`,
      '',
      `Each bot guide is a separate message below ⬇️`,
    ].join('\n'),
    [
      `## 1️⃣ DANTE BOT (this bot — already running)`,
      '',
      `**How to run:**`,
      `\`\`\``,
      `node dante-bot.js                  → normal start`,
      `node dante-bot.js --keepalive      → auto-restart on crash`,
      `node dante-bot.js --setup          → full wipe + rebuild`,
      `node dante-bot.js --nuke           → nuclear wipe (asks confirm)`,
      `node dante-bot.js --roles          → rebuild roles only`,
      `node dante-bot.js --channels       → rebuild channels only`,
      `node dante-bot.js --messages       → repost all messages`,
      `node dante-bot.js --guides         → repost bot guides`,
      `\`\`\``,
      '',
      `**Role to assign:** 🤖 Dante Bot`,
      `**Commands:** type \`!help\` in any channel`,
      '',
      `**For 24/7 uptime without keeping PC on:**`,
      `Free: Railway.app → New Project → Deploy from GitHub → upload bot file`,
      `Paid: any VPS (DigitalOcean, Vultr, etc.) → run with --keepalive`,
    ].join('\n'),
    [
      `## 2️⃣ CARL-BOT — Reaction Roles`,
      '',
      `**Invite:** https://carl.gg`,
      `**Role to assign:** 🤖 carl-bot`,
      '',
      `**Setup reaction roles for #🎭-get-roles:**`,
      `1. Go to https://carl.gg → select your server → **Reaction Roles**`,
      `2. Click **New Reaction Role Group**`,
      `3. Set channel to \`🎭-get-roles\``,
      `4. Set mode to **Toggle** (so members can add AND remove)`,
      `5. Add these pairs:`,
      `\`\`\``,
      `⚔️   →   ⚔️ Knight`,
      `🎬  →   🎬 YouTube Fan`,
      `🎈  →   🎈 LaLoon Fan`,
      `🏆  →   🏆 TH18`,
      `🔥  →   🔥 TH17`,
      `⭐  →   ⭐ TH16`,
      `\`\`\``,
      `6. Click Save ✅`,
      '',
      `**Tip:** You can also use Carl-bot for automod, custom commands, and welcome messages.`,
    ].join('\n'),
    [
      `## 3️⃣ CLASHKING — War Tracking + Legend League + Clan Management`,
      '',
      `**Invite:** https://clashk.ing`,
      `**Role to assign:** 🤖 ClashKing`,
      `**Your clan tag:** ${cfg.CLAN_TAG}`,
      '',
      `**Initial setup (run these slash commands in any channel):**`,
      `\`\`\``,
      `/clan link ${cfg.CLAN_TAG}`,
      `\`\`\``,
      '',
      `**War tracking — posts war start/end + missed attacks:**`,
      `\`\`\``,
      `/war setup channel:#⚔️-war-chat`,
      `/war missedattacks channel:#📋-ban-log`,
      `/war result channel:#🏅-war-results`,
      `\`\`\``,
      '',
      `**Legend League — daily recap at season reset:**`,
      `\`\`\``,
      `/legend setup channel:#👑-legend-hits`,
      `/legend profile [playertag]       ← see anyone's legend stats`,
      `/legend stats                     ← your own season summary`,
      `/legend roster                    ← all clan legend players`,
      `\`\`\``,
      '',
      `**Auto-roles — syncs Discord roles with CoC clan rank:**`,
      `\`\`\``,
      `/autorole setup`,
      `\`\`\``,
      `Then map roles like:`,
      `\`\`\``,
      `Co-leader → 🦁 Hand of the King`,
      `Elder     → 📜 Maester`,
      `Member    → ⚔️ Knight`,
      `\`\`\``,
      '',
      `**CWL tracking:**`,
      `\`\`\``,
      `/cwl setup channel:#🏆-cwl`,
      `/cwl roster`,
      `/cwl stats`,
      `\`\`\``,
      '',
      `**Clan Games leaderboard:**`,
      `\`\`\``,
      `/clangames setup channel:#📣-announcements`,
      `\`\`\``,
      '',
      `**Capital tracking (Clan Capital raids):**`,
      `\`\`\``,
      `/capital setup channel:#📣-announcements`,
      `\`\`\``,
      '',
      `**Other useful commands:**`,
      `\`\`\``,
      `/player [tag]                     ← full player profile`,
      `/clan members                     ← list with TH levels`,
      `/war attacks                      ← current war attack log`,
      `/donations                        ← donation leaderboard`,
      `\`\`\``,
    ].join('\n'),
    [
      `## 4️⃣ CLASHPERK — Stats, CWL, Donations, Activity`,
      '',
      `**Invite:** https://clashperk.com`,
      `**Role to assign:** 🤖 ClashPerk`,
      '',
      `**Initial setup:**`,
      `\`\`\``,
      `/setup clan ${cfg.CLAN_TAG}`,
      `\`\`\``,
      '',
      `**War feed — live war status updates:**`,
      `\`\`\``,
      `/setup wars channel:#⚔️-war-chat`,
      `\`\`\``,
      '',
      `**CWL and donation tracking:**`,
      `\`\`\``,
      `/setup cwl channel:#🏆-cwl`,
      `/setup donations channel:#📣-announcements`,
      `\`\`\``,
      '',
      `**Member activity + join/leave logs:**`,
      `\`\`\``,
      `/setup memberlogs channel:#📋-ban-log`,
      `/lastseen [playertag]             ← when they last attacked`,
      `/activity                         ← activity heatmap`,
      `\`\`\``,
      '',
      `**Export to Google Sheets:**`,
      `\`\`\``,
      `/export clan                      ← all member stats to CSV`,
      `/export war                       ← war history to CSV`,
      `\`\`\``,
    ].join('\n'),
    [
      `## 5️⃣ YOUTUBE AUTO-POSTS (free via IFTTT)`,
      '',
      `**Why IFTTT?** MEE6 YouTube alerts need premium. IFTTT is 100% free.`,
      '',
      `**Setup:**`,
      `1. Go to https://ifttt.com → sign up free → click **Create**`,
      `2. **If This** → search YouTube → choose **New video by a specific channel**`,
      `3. Paste your YouTube Channel ID`,
      `   → Get it at: https://www.youtube.com/account_advanced`,
      '',
      `4. **Then That** → search Webhooks → choose **Make a web request**`,
      `5. Get your Discord webhook:`,
      `   Edit #🎬-new-videos → Integrations → Webhooks → New Webhook → Copy URL`,
      '',
      `6. In IFTTT webhook:`,
      `   URL: [paste Discord webhook URL]`,
      `   Method: POST`,
      `   Content-Type: application/json`,
      `   Body:`,
      `   \`{"content": "@everyone 🎬 New video from Dante CoC! {{Url}}"}\``,
      '',
      `7. Save → Finish ✅`,
      '',
      `**Test it:** Click "Check now" in IFTTT after uploading a video.`,
    ].join('\n'),
    [
      `## ⚠️ CRITICAL — BOT ROLE ORDER`,
      '',
      `In **Server Settings → Roles**, drag roles into this exact order (top = highest):`,
      `\`\`\``,
      `🐉 King              ← top staff`,
      `🦁 Hand of the King`,
      `📜 Maester`,
      `──────────────────── ← bots go here, ABOVE member roles`,
      `🤖 Dante Bot`,
      `🤖 ClashKing`,
      `🤖 ClashPerk`,
      `🤖 carl-bot`,
      `🤖 MEE6`,
      `────────────────────`,
      `⚔️ Knight`,
      `🎬 YouTube Fan`,
      `🎈 LaLoon Fan`,
      `🛡️ Recruit`,
      `🏆 TH18`,
      `🔥 TH17`,
      `⭐ TH16`,
      `@everyone            ← always at bottom`,
      `\`\`\``,
      '',
      `**Why this matters:** Bots can only manage roles that are BELOW them in the list.`,
      `If ClashKing is below ⚔️ Knight, it cannot assign Knight to members — it will silently fail.`,
    ].join('\n'),
    [
      `## 💣 NUKE & REBUILD GUIDE`,
      '',
      `Need to start fresh or make big changes? Use the rebuild flags:`,
      '',
      `**Full nuclear wipe + rebuild (Discord confirm required):**`,
      `\`\`\``,
      `node dante-bot.js --nuke`,
      `Then type: !nuke confirm    (in #💣-nuke-confirm channel, King role only)`,
      `\`\`\``,
      '',
      `**Partial rebuilds (faster, no wipe):**`,
      `\`\`\``,
      `node dante-bot.js --roles       → delete + recreate all roles`,
      `node dante-bot.js --channels    → rebuild channel structure`,
      `node dante-bot.js --messages    → repost messages in empty channels`,
      `node dante-bot.js --guides      → repost bot setup guides`,
      `\`\`\``,
      '',
      `**To change a channel name or role color:**`,
      `1. Edit the name/color in config.js`,
      `2. Run \`node dante-bot.js --roles\` or \`--channels\``,
      `   (This will delete + recreate — members keep their roles via the startup cleanup)`,
      '',
      `**To add a new channel:**`,
      `1. Add an entry in CHANNEL_LAYOUT in config.js`,
      `2. Run \`node dante-bot.js --channels\``,
      '',
      `**To add a new role:**`,
      `1. Add an entry in ROLE_DEFINITIONS in config.js`,
      `2. Run \`node dante-bot.js --roles\``,
      '',
      `**Tip:** Always run \`--setup --keepalive\` on a fresh deploy to set everything up AND stay live.`,
    ].join('\n'),
  ];
}

module.exports = { buildGuides };