'use strict';

function buildGuides(cfg) {
  return [
    [
      '# 🤖 Vergil Setup',
      '',
      'Use this bot first, then add free community tools before paying for anything.',
      '',
      '**What this setup gives you:**',
      '• Cleaner onboarding',
      '• Better badges and intro flow',
      '• Safer war organization',
      '• Free-first bot stack',
    ].join('\n'),
    [
      '## 1️⃣ Discord Built-Ins First',
      '',
      '**Use the platform before extra bots:**',
      '• Community server onboarding',
      '• Role-exclusive channels',
      '• Polls',
      '• Text and voice channels',
      '• Screen share / Go Live',
      '• Per-server profiles',
    ].join('\n'),
    [
      '## 2️⃣ Carl-bot For Free Tools',
      '',
      '**Best free Carl-bot uses:**',
      '• Reaction roles',
      '• Greetings and farewell messages',
      '• Logging and moderation',
      '• Automod and custom commands',
      '• Suggestions and notifications',
      '',
      '**Invite:** https://carl.gg',
      '**Why here:** this covers most server needs without paying.',
    ].join('\n'),
    [
      '## 3️⃣ YAGPDB As The Free Backup',
      '',
      '**Use YAGPDB when you want more control:**',
      '• Open-source and self-hostable',
      '• Reaction roles',
      '• Automod and modlogs',
      '• Feeds and custom commands',
      '• Join / leave messages',
      '',
      '**Website:** https://yagpdb.xyz',
      '**Best for:** server owners who want a free, flexible fallback.',
    ].join('\n'),
    [
      '## 4️⃣ Discord Cards We Now Use',
      '',
      '**Interact with these server panels:**',
      '• Badge picker in #🎭-get-roles',
      '• Intro templates in #👋-introductions',
      '• Card-based onboarding messages',
      '• Cleaner command replies',
      '',
      '**Tip:** delete old panel messages if you want a fresh repost.',
    ].join('\n'),
    [
      '## 5️⃣ ClashKing / ClashPerk',
      '',
      '**Free setup focus:**',
      '• Link the clan tag',
      '• Set war and legend channels',
      '• Keep donation and activity logs organized',
      '',
      '**Free-first rule:** only add premium features when a hard limit blocks you.',
    ].join('\n'),
    [
      '## 6️⃣ YouTube Alerts Free',
      '',
      '**Use IFTTT instead of premium alert bots:**',
      '1. Create a free IFTTT account',
      '2. Trigger on new YouTube video',
      '3. Send to a Discord webhook',
      '4. Post into #🎬-new-videos',
      '',
      '**Result:** free upload alerts without paying for MEE6.',
    ].join('\n'),
    [
      '## 7️⃣ Role Order + Rebuild',
      '',
      '**Keep roles in this order:**',
      'King → Hand → Maester → bots → member roles → Recruit/TH badges → @everyone',
      '',
      '**Rebuild commands:**',
      'node dante-bot.js --roles',
      'node dante-bot.js --channels',
      'node dante-bot.js --messages',
      'node dante-bot.js --guides',
      'node dante-bot.js --nuke',
      '',
      '**Tip:** use `node index.js --setup --keepalive` for a fresh deploy.',
    ].join('\n'),
  ];
}

module.exports = { buildGuides };